# Documentation for all additional configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" # "pip" is the YAML value for "Poetry" package manager
    directory: "./"
    schedule:
      interval: "daily"
