# Documentation for all additional configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "poetry"
    directory: "./"
    schedule:
      interval: "daily"
